Repository Halleck45/ast-metrics, pull requests merged in 2024-11, with the labels that each got.

#66 CI for accessibility of HTML report
  .github/workflows/test.yml
  lighthouserc.json
  src/Report/Html/templates/compare.html
  src/Report/Html/templates/componentChartRadiusBarAfferent.html
  src/Report/Html/templates/componentChartRadiusBarComplexity.html
  src/Report/Html/templates/componentChartRadiusBarEfferent.html
  src/Report/Html/templates/componentChartRadiusBarInstability.html
  src/Report/Html/templates/componentChartRadiusBarMaintainability.html
  src/Report/Html/templates/componentDependencyDiagram.html
  src/Report/Html/templates/componentTableCompareBranch.html
  src/Report/Html/templates/componentTableRisks.html
  src/Report/Html/templates/index.html
  src/Report/Html/templates/layout.html
Labels: enhancement

#67 fixes calculations and dashboard for Golang
  src/Analyzer/Aggregator.go
  src/Analyzer/Volume/LocVisitor.go
  src/Analyzer/Volume/LocVisitor_test.go
  src/Engine/Engine.go
  src/Engine/Golang/GolangRunner.go
  src/Engine/Php/PhpRunner.go
  src/Engine/Python/PythonRunner.go
  src/Engine/util.go
  src/Report/Html/HtmlReportGenerator.go
  src/Report/Html/templates/componentChartRadiusBarLoc.html
  src/Ui/ComponentBarchartCyclomaticByMethodRepartition.go
Labels: bug

#68 Improving DX, adding a --ci option and listing generated reports in output
  main.go
  src/Cli/ScreenEnd.go
  src/Cli/ScreenHome.go
  src/Cli/ScreenHome_test.go
  src/Cli/ScreenHtmlReport.go
  src/Command/AnalyzeCommand.go
  src/Configuration/Configuration.go
  src/Configuration/ConfigurationLoader.go
  src/Report/GeneratedReport.go
  src/Report/Html/HtmlReportGenerator.go
  src/Report/Json/JsonReportGenerator.go
  src/Report/Json/JsonReportGenerator_test.go
  src/Report/Markdown/MardownReportGenerator_test.go
  src/Report/Markdown/MarkdownReportGenerator.go
  src/Report/Reporter.go
Labels: enhancement

#70 Added the `--report-openmetrics` option, allowing OpenMetrics reports
  go.mod
  go.sum
  main.go
  src/Command/AnalyzeCommand.go
  src/Configuration/Configuration.go
  src/Report/OpenMetrics/OpenMetricsGenerator.go
  src/Report/OpenMetrics/OpenMetricsGenerator_test.go
Labels: enhancement

#71 Make the download script compatible with sh
  scripts/download.sh
Labels: enhancement

#73 make contribution easier
  .github/CONTRIBUTING.md
  src/Cli/ScreenHtmlReport.go
  src/Command/AnalyzeCommand.go
  src/Engine/Engine.go
  src/Report/HtmlReportGenerator.go
  src/Report/JsonReportGenerator.go
  src/Report/JsonReportGenerator_test.go
  src/Report/MardownReportGenerator_test.go
  src/Report/MarkdownReportGenerator.go
  src/Report/OpenMetricsGenerator.go
  src/Report/OpenMetricsGenerator_test.go
  src/Report/Reporter.go
  src/Report/ReportersFactory.go
  src/Report/templates/html/compare.html
  src/Report/templates/html/componentChartRadiusBar.html
  src/Report/templates/html/componentChartRadiusBarAfferent.html
  src/Report/templates/html/componentChartRadiusBarComplexity.html
  src/Report/templates/html/componentChartRadiusBarEfferent.html
  src/Report/templates/html/componentChartRadiusBarInstability.html
  src/Report/templates/html/componentChartRadiusBarLoc.html
  src/Report/templates/html/componentChartRadiusBarMaintainability.html
  src/Report/templates/html/componentComparaisonBadge.html
  src/Report/templates/html/componentComparaisonOperator.html
  src/Report/templates/html/componentDependencyDiagram.html
  src/Report/templates/html/componentTableCompareBranch.html
  src/Report/templates/html/componentTableRisks.html
  src/Report/templates/html/index.html
  src/Report/templates/html/layout.html
  src/Report/templates/html/risks.html
  src/Report/templates/markdown/index.md
  src/Report/types.go
Labels: documentation, enhancement

#75 Speedup Git analysis
  src/Analyzer/GitAnalyzer.go
  src/Scm/Commit.go
  src/Scm/GitRepository.go
Labels: enhancement
